#pragma config(Motor,  port2,           RickFL,        tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port3,           ChrisFR,       tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port4,           HenryBL,       tmotorVex269_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           GriffinBR,     tmotorVex269_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int speed = 127;
	int frx = -1;
	int flx = +1;
	int brx = -1;
	int blx = +1;

	while(true){
		motor[ChrisFR] = speed * frx;
		motor[GriffinBR] = speed * brx;
		motor[HenryBL] = speed * blx;
		motor[RickFL] = speed * flx;

	}


}
