#pragma config(Motor,  motor2,          RickFL,        tmotorVexIQ, openLoop)
#pragma config(Motor,  motor3,          ChrisFR,       tmotorVexIQ, openLoop)
#pragma config(Motor,  motor4,          HenryBL,       tmotorVexIQ, openLoop)
#pragma config(Motor,  motor5,          GriffinBR,     tmotorVexIQ, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int speed = 90;
	int frx = +1;
	int flx = -1;
	int brx = +1;
	int blx = -1;

	while(true){
		motor[ChrisFR] = speed * frx;
		motor[GriffinBR] = speed * brx;
		motor[HenryBL] = speed * blx;
		motor[RickFL] = speed * flx;
	}
}
