#pragma config(Motor,  port2,           RickFL,        tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port3,           ChrisFR,       tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port4,           HenryRL,       tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port5,           GriffinRR,     tmotorVex269_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true){
		startMotor(ChrisFR,127);
		startMotor(GriffinRR,127);
		startMotor(HenryRL,127);
		startMotor(RickFL,127);
	}
}
